In [1]:
#import pandas
import pandas as pd

In [14]:
#import data and create data frame
df = pd.read_csv("data/unusured-wage-workers.csv", skiprows=6)
df

,Recoded detailed Hispanic origin,Total,Total Selected Geographies,Alabama,Alaska,Arizona,Arkansas,California,Colorado,Connecticut,...,Michigan.1,Minnesota.1,Mississippi.1,Missouri.1,Montana.1,Nebraska.1,Nevada.1,New Hampshire.1,New Jersey.1,New Mexico.1
0,-> Total,194477570,41397800,991076,163177,1510121,812876,10381445,1045209,784424,...,7762092,4647152,2254163,5223077,845904,1683360,2466307,1182008,7598206,1398784
1,Not Spanish/Hispanic/Latino,156345007,29046882,922531,150918,799713,738201,4582664,649281,526720,...,7399706,4429745,2184413,5007160,816972,1512414,1785513,1139948,6238273,774648
2,Mexican,23060400,8049626,45261,4915,642101,56955,4875645,299828,18371,...,250430,132872,36099,136646,19611,124558,506069,8150,151900,386214
3,Puerto Rican,3375309,1121209,6882,2704,11117,2427,58233,9719,153322,...,27115,12091,7060,15808,1158,4396,21308,11745,326014,6788
4,Cuban,2014133,477347,1838,304,3915,724,24101,2889,3473,...,10373,5884,2569,6027,703,5616,23969,1688,75150,3972
5,Dominican,975256,357600,921,1067,994,189,4007,1366,25331,...,6529,2568,1393,2418,82,701,3258,7653,209984,1618
6,Costa Rican,111442,20201,0,0,376,126,4892,164,1294,...,1780,931,351,1259,144,350,1923,392,16748,270
7,Guatemalan,1117944,397224,7132,13,7644,1349,197027,2484,8209,...,8010,8134,4668,7821,209,10844,16902,591,47974,2195
8,Honduran,543100,160445,804,107,1167,1321,41806,1746,3211,...,3267,2732,3346,4348,89,2082,4648,1165,38873,1163
9,Nicaraguan,350783,88533,70,132,726,40,33012,790,215,...,971,2403,773,1065,213,441,5481,113,6881,572
10,Panamanian,122698,20834,194,0,689,29,3983,873,499,...,1939,986,646,1539,177,323,2400,127,6005,679
11,Salvadoran,1457556,510048,879,554,5185,6567,289984,6108,3467,...,4206,8432,1167,6289,122,6865,32228,1225,54574,1941
12,Other Central American,28145,9653,0,0,95,113,5097,0,298,...,10,57,0,74,0,195,686,0,336,14
13,Argentinean,201453,28427,0,0,434,0,9758,1051,596,...,1957,1972,162,1039,146,388,2894,554,15154,435
14,Bolivian,59540,10517,0,0,107,0,2754,105,125,...,549,456,134,409,28,298,1023,0,3847,477
15,Chilean,111490,17315,50,0,367,25,4886,622,715,...,1568,1269,132,604,182,974,1350,249,8677,494
16,Colombian,893748,157356,144,601,1628,139,19467,1916,7285,...,4990,6437,1658,4335,607,1323,7284,2207,113829,2398
17,Ecuadorian,406265,100808,67,67,328,28,9191,291,13118,...,2113,10070,500,919,49,288,1442,408,102646,740
18,Paraguayan,16276,2377,0,71,9,0,370,0,236,...,160,360,171,83,54,9,107,0,2471,69
19,Peruvian,468251,98774,50,28,1355,170,29017,1237,6279,...,3114,2666,675,2120,128,924,6413,981,65250,1272
20,Uruguayan,50312,10509,0,0,0,0,737,0,300,...,191,471,8,92,0,57,484,336,8143,92
21,Venezuelan,392927,55552,119,102,549,29,2734,589,1044,...,2835,1797,605,2562,209,801,2298,192,12561,589
22,Other South American,18323,3693,0,0,59,0,1203,99,389,...,194,199,0,40,0,0,175,28,1665,49
23,Spaniard,612299,125008,710,270,7794,1063,33951,12642,808,...,7729,3864,1993,5888,1781,1456,11808,1316,30364,54040
24,All Other Spanish/Hispanic/Latino,1744913,527862,3424,1324,23769,3381,146926,51409,9119,...,22356,10756,5640,14532,3240,8057,26644,2940,60887,158055